name: project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  animated_bottom_navigation_bar: ^1.4.0
  fl_chart: ^0.70.2
  time_picker_spinner: ^1.0.2
  wheel_picker: ^0.2.1
  flutter_bloc: ^9.1.0
  loader_overlay: ^5.0.0
  dio: ^5.8.0+1
  dartz: ^0.10.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
